--
--  The following problem is take from Project Euler:
--
--                 https://projecteuler.net/problem=2
--
--  Even Fibonacci numbers
--  ----------------------
--
--  Each new term in the Fibonacci sequence is generated by adding the
--  previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
--                 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--  By considering the terms in the Fibonacci sequence whose values do not
--  exceed four million, find the sum of the even-valued terms.

with Ada.Text_IO;

procedure P0002_Even_Fibonacci_Numbers is

   Term_1  : Natural := 1;
   Term_2  : Natural := 2;
   Term_3  : Natural := Term_1 + Term_2;
   Σ_terms : Natural := 2;

begin

   loop
      if Term_3 mod 2 = 0 then
         Σ_terms := @ + Term_3;
      end if;

      Term_1 := Term_2;
      Term_2 := Term_3;
      Term_3 := Term_1 + Term_2;

      exit when Term_3 > 4_000_000;
   end loop;

   Ada.Text_IO.Put_Line ("Answer" & Σ_terms'Image);

end P0002_Even_Fibonacci_Numbers;
