--
--  The following problem is take from Project Euler:
--
--                 https://projecteuler.net/problem=12
--
--  Highly divisible triangular number
--  ----------------------------------
--
--  The sequence of triangle numbers is generated by adding the natural
--  numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
--  28. The first ten terms would be:
--
--                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
--  Let us list the factors of the first seven triangle numbers:
--
--                  1: 1
--                  3: 1,3
--                  6: 1,2,3,6
--                 10: 1,2,5,10
--                 15: 1,3,5,15
--                 21: 1,3,7,21
--                 28: 1,2,4,7,14,28
--
--  We can see that 28 is the first triangle number to have over five
--  divisors. What is the value of the first triangle number to have over
--  five hundred divisors?

with Ada.Text_IO;
with Euler_Tools;

procedure P0012_Highly_Divisible_Triangular_Number is

   package Natural_Tools is new Euler_Tools (Natural);
   use Natural_Tools;

   Factors_List : List_Type;
   Counter      : Natural := 8;
   Answer       : Natural;

begin

   loop
      Answer       := Sum_Sequence (Counter);
      Factors_List := Factors (Answer);

      exit when Natural (Factors_List.Length) > 500;

      Factors_List.Clear;
      Counter := @ + 1;
   end loop;

   Ada.Text_IO.Put_Line ("Answer:" & Answer'Image);

end P0012_Highly_Divisible_Triangular_Number;
