-------------------------------------------------------------------------------
--
--  Copyright (c) 2023 Francesc Rocher <francesc.rocher@gnail.com>
--  SPDX-License-Identifier: CC-BY-NC-SA-4.0
--  https://creativecommons.org/licenses/by-nc-sa/4.0/
--
--  ---------------------------------------------------------------------------
--
--  The following problem is taken from Project Euler:
--
--                 https://projecteuler.net/problem=29
--
--  Distinct powers
--  ---------------
--
--  Consider all integer combinations of a^b for  2 ≤ a ≤ 5  and  2 ≤ b ≤ 5:
--
--                 2^2=4,  2^3=8,   2^4=16,  2^5=32
--                 3^2=9,  3^3=27,  3^4=81,  3^5=243
--                 4^2=16, 4^3=64,  4^4=256, 4^5=1024
--                 5^2=25, 5^3=125, 5^4=625, 5^5=3125
--
--  If they are then placed in numerical order, with any repeats removed, we
--  get the following sequence of 15 distinct terms:
--
--      4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
--
--  How many distinct terms are in the sequence generated by a^b for
--
--             2 ≤ a ≤ 100  and  2 ≤ b ≤ 100?
--
-------------------------------------------------------------------------------

with Problem_Interface; use Problem_Interface;

package P0029_Distinct_Powers is

   type P0029_Type is new Problem_Type with null record;

   overriding function Get_Number (P : P0029_Type) return Natural is (29);

   overriding function Get_Title (P : P0029_Type) return String is
     ("Distinct power");

   overriding function Get_Brief (P : P0029_Type) return String is
     ("How many distinct terms are in the sequence generated by a^b for " &
      "2 <= a <= 100  and  2 <= b <= 100?");

   overriding function Get_Answer (P : P0029_Type) return String;

   overriding function Get_Notes (P : P0029_Type) return String is ("");
end P0029_Distinct_Powers;
